import Link from "next/link";

const features = [
  { n: "01", title: "One network control plane", body: "Customers, subscribers, sessions, routers, AAA, billing and operations in one coherent workspace." },
  { n: "02", title: "Billing that understands access", body: "Packages, subscriptions, vouchers and payment state connect directly to service entitlement." },
  { n: "03", title: "Vendor-neutral by design", body: "MikroTik, RADIUS, hotspot and future network adapters sit behind clear provider boundaries." },
  { n: "04", title: "Evidence before claims", body: "Live state is shown only when an authoritative source is connected. No invented uptime, revenue or device counts." },
];
const capabilities = ["PPPoE & Hotspot", "RADIUS / AAA", "MikroTik control", "Billing & payments", "Vouchers", "QoS & bandwidth", "Sessions & accounting", "Network monitoring", "Multi-site operations", "Reports & analytics"];
function NetworkGlyph({ large = false }) { return <svg className={large ? "network-glyph network-glyph-large" : "network-glyph"} viewBox="0 0 96 72" fill="none" aria-hidden="true"><path d="M8 26C29 5 67 5 88 26" /><path d="M22 40c14-14 38-14 52 0" /><path d="M37 53c6-7 16-7 22 0" /><circle cx="48" cy="63" r="4" /><circle cx="48" cy="63" r="12" className="glyph-ring" /></svg>; }

export default function Home() {
  return <main className="jaslyn-landing">
    <div className="landing-grid" aria-hidden="true" /><div className="landing-glow glow-one" aria-hidden="true" /><div className="landing-glow glow-two" aria-hidden="true" />
    <nav className="landing-nav">
      <Link href="/" className="landing-brand"><span className="brand-symbol"><NetworkGlyph /></span><span><strong>JASLYN <em>NET</em></strong><small>NETWORK OPERATING FABRIC</small></span></Link>
      <div className="landing-links"><a href="#platform">Platform</a><a href="#architecture">Architecture</a><a href="#operators">For operators</a></div>
      <div className="landing-nav-actions"><Link href="/login" className="nav-login">Sign in</Link><Link href="/register" className="nav-cta">Create workspace <span>↗</span></Link></div>
    </nav>
    <section className="landing-hero">
      <div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> HYBRID NETWORK OPERATIONS / 01</div><h1>Run the network.<br /><span>Not the paperwork.</span></h1><p className="hero-lede">Jaslyn Net unifies subscriber management, access control, billing, payments and network operations into one operational fabric.</p><div className="hero-actions"><Link href="/register" className="hero-primary">Start building your network <span>→</span></Link><Link href="/login" className="hero-secondary">Open console <span>↗</span></Link></div><div className="hero-proof"><span><i /> Real-source state</span><span><i /> Multi-site ready</span><span><i /> Vendor-neutral core</span></div></div>
      <div className="hero-visual"><div className="visual-frame"><div className="visual-top"><span><i /> NETWORK FABRIC</span><small>LIVE CONTROL SURFACE</small></div><div className="fabric"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="fabric-node internet"><span>01</span><b>UPLINK</b><small>INTERNET</small></div><div className="fabric-node core"><NetworkGlyph large /><b>JASLYN CORE</b><small>POLICY + AAA + BILLING</small></div><div className="fabric-node node-a"><span>02</span><b>GATEWAY</b><small>ROUTEROS</small></div><div className="fabric-node node-b"><span>03</span><b>ACCESS</b><small>HOTSPOT / PPPoE</small></div><div className="fabric-node node-c"><span>04</span><b>SUBSCRIBERS</b><small>ENTITLEMENTS</small></div><div className="connection c1" /><div className="connection c2" /><div className="connection c3" /><div className="connection c4" /></div><div className="visual-footer"><span><i className="green" /> CONTROL PLANE</span><span><i className="cyan" /> DATA PLANE</span><span><i className="gold" /> COMMERCIAL PLANE</span></div></div></div>
    </section>
    <section className="signal-strip"><div><b>JASLYN NET</b><span>01</span></div><div><b>SUBSCRIBERS</b><span>02</span></div><div><b>NETWORK</b><span>03</span></div><div><b>REVENUE</b><span>04</span></div><div><b>OBSERVABILITY</b><span>05</span></div></section>
    <section id="platform" className="landing-section"><div className="section-intro"><span className="eyebrow">THE PLATFORM / 02</span><h2>One fabric.<br /><span>Every operational layer.</span></h2><p>Designed around the way modern ISPs actually work: access, identity, money and infrastructure are connected, so the software should be too.</p></div><div className="feature-grid">{features.map((f)=><article className="feature-card" key={f.n}><span>{f.n}</span><div><h3>{f.title}</h3><p>{f.body}</p></div><b>↗</b></article>)}</div></section>
    <section id="architecture" className="architecture-section"><div className="architecture-panel"><div className="section-intro compact"><span className="eyebrow">ARCHITECTURE / 03</span><h2>Built to sit between<br /><span>business and network.</span></h2></div><div className="architecture-layers"><div><small>BUSINESS PLANE</small><b>Customers · Billing · Payments</b></div><i /><div><small>CONTROL PLANE</small><b>Policy · Entitlement · AAA · Automation</b></div><i /><div><small>NETWORK PLANE</small><b>MikroTik · RADIUS · Hotspot · PPPoE</b></div></div></div><div className="capability-panel"><span className="eyebrow">CAPABILITY MAP</span><div className="capability-list">{capabilities.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></div></section>
    <section id="operators" className="operator-section"><div><span className="eyebrow">FOR OPERATORS / 04</span><h2>Your NOC, billing desk<br /><span>and subscriber system.</span></h2><p>Jaslyn Net is designed for teams that need operational truth at a glance, not another dashboard full of decorative numbers.</p></div><div className="operator-quote"><NetworkGlyph /><strong>Evidence over claims.</strong><span>Every important state should have an authoritative source behind it.</span></div></section>
    <footer className="landing-footer"><div className="landing-brand"><span className="brand-symbol"><NetworkGlyph /></span><span><strong>JASLYN <em>NET</em></strong><small>HYBRID NETWORK OPERATING FABRIC</small></span></div><div><Link href="/login">Sign in</Link><Link href="/register">Create workspace</Link><Link href="/net">Console</Link></div><small>© 2026 Jaslyn Net · Vendor-neutral network operations</small></footer>
  </main>;
}