import Link from "next/link";

const features=[
 {n:"01",title:"Subscriber lifecycle",body:"Provision, suspend, renew, upgrade, migrate and audit subscribers from one service-aware identity record."},
 {n:"02",title:"Access fabric",body:"PPPoE, Hotspot, static IP and policy-based access sit behind a shared entitlement model."},
 {n:"03",title:"Network command fabric",body:"Operate supported routers and access systems through explicit provider adapters and capability boundaries."},
 {n:"04",title:"Billing + reconciliation",body:"Invoices, payments, activation, accounting and reconciliation follow one auditable lifecycle instead of disconnected scripts."},
 {n:"05",title:"NOC + observability",body:"Sessions, devices, health, incidents, telemetry and service impact belong in the same operational context."},
 {n:"06",title:"Automation with guardrails",body:"Turn repeatable work into verified workflows with idempotency, audit trails, retries and fail-closed controls."},
];
const capabilities=["PPPoE","Hotspot / Captive Portal","Static IP","RADIUS / AAA","CoA / Session Control","MikroTik","Omada","OpenWrt","OPNsense","FreeRADIUS","IPAM","Bandwidth & QoS","FUP Policies","Vouchers","Resellers & Agents","Invoices","M-Pesa","Payment Reconciliation","Notifications","Customer Self-Service","Network Monitoring","Incidents","Multi-WAN","Failover","Multi-Site","Audit Logs","Webhooks","REST APIs","Automation","Analytics"];
const planes=[
 {tag:"01",title:"COMMERCIAL PLANE",items:"Customers · Packages · Invoices · Payments · Wallets"},
 {tag:"02",title:"SERVICE PLANE",items:"Entitlements · Subscriptions · Provisioning · Lifecycle"},
 {tag:"03",title:"IDENTITY PLANE",items:"RADIUS · AAA · Policies · Sessions · Accounting"},
 {tag:"04",title:"NETWORK PLANE",items:"Routers · Access · IPAM · QoS · Telemetry"},
 {tag:"05",title:"OPERATIONS PLANE",items:"NOC · Incidents · Automation · Audit · Reconciliation"}
];
function NetworkGlyph({large=false}){return <svg className={large?"network-glyph network-glyph-large":"network-glyph"} viewBox="0 0 96 72" fill="none" aria-hidden="true"><path d="M8 26C29 5 67 5 88 26"/><path d="M22 40c14-14 38-14 52 0"/><path d="M37 53c6-7 16-7 22 0"/><circle cx="48" cy="63" r="4"/><circle cx="48" cy="63" r="12" className="glyph-ring"/></svg>}

export default function Home(){return <main className="jaslyn-landing">
<div className="landing-grid" aria-hidden="true"/><div className="landing-glow glow-one" aria-hidden="true"/><div className="landing-glow glow-two" aria-hidden="true"/>
<nav className="landing-nav"><Link href="/" className="landing-brand"><span className="brand-symbol"><NetworkGlyph/></span><span><strong>JASLYN <em>NET</em></strong><small>UNIVERSAL CONNECTIVITY OPERATING FABRIC</small></span></Link><div className="landing-links"><a href="#platform">Platform</a><a href="#fabric">Fabric</a><a href="#architecture">Architecture</a><a href="#operators">Operators</a></div><div className="landing-nav-actions"><Link href="/login" className="nav-login">Sign in</Link><Link href="/register" className="nav-cta">Create workspace <span>↗</span></Link></div></nav>
<section className="landing-hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> HYBRID NETWORK OPERATIONS / 01</div><h1>One fabric.<br/><span>Every connection.</span></h1><p className="hero-lede">Jaslyn Net brings subscribers, access, identity, billing, payments, network control, observability and automation into one vendor-neutral operating layer.</p><div className="hero-actions"><Link href="/register" className="hero-primary">Build your network <span>→</span></Link><Link href="/login" className="hero-secondary">Open console <span>↗</span></Link></div><div className="hero-proof"><span><i/> Source-backed state</span><span><i/> Hybrid access</span><span><i/> Provider boundaries</span><span><i/> Auditable actions</span></div></div>
<div className="hero-visual"><div className="visual-frame"><div className="visual-top"><span><i/> JASLYN FABRIC</span><small>CONTROL • DATA • COMMERCIAL</small></div><div className="fabric"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="fabric-node internet"><span>01</span><b>UPLINK</b><small>INTERNET</small></div><div className="fabric-node core"><NetworkGlyph large/><b>JASLYN CORE</b><small>POLICY · AAA · BILLING</small></div><div className="fabric-node node-a"><span>02</span><b>NETWORK EDGE</b><small>ROUTER / GATEWAY</small></div><div className="fabric-node node-b"><span>03</span><b>ACCESS</b><small>PPPoE / HOTSPOT</small></div><div className="fabric-node node-c"><span>04</span><b>SUBSCRIBERS</b><small>ENTITLEMENTS</small></div><div className="connection c1"/><div className="connection c2"/><div className="connection c3"/><div className="connection c4"/></div><div className="visual-footer"><span><i className="green"/> CONTROL</span><span><i className="cyan"/> DATA</span><span><i className="gold"/> COMMERCIAL</span></div></div></div></section>
<section className="signal-strip"><div><b>ACCESS</b><span>01</span></div><div><b>IDENTITY</b><span>02</span></div><div><b>REVENUE</b><span>03</span></div><div><b>NETWORK</b><span>04</span></div><div><b>OPERATIONS</b><span>05</span></div></section>
<section id="platform" className="landing-section"><div className="section-intro"><span className="eyebrow">THE PLATFORM / 02</span><h2>More than billing.<br/><span>More than network management.</span></h2><p>Modern ISP operations cross boundaries. Jaslyn Net is structured around the full lifecycle from payment and entitlement to identity, access, session, accounting, enforcement and reconciliation.</p></div><div className="feature-grid">{features.map(f=><article className="feature-card" key={f.n}><span>{f.n}</span><div><h3>{f.title}</h3><p>{f.body}</p></div><b>↗</b></article>)}</div></section>
<section id="fabric" className="fabric-section"><div className="section-intro"><span className="eyebrow">HYBRID CAPABILITY FABRIC / 03</span><h2>Connect the pieces.<br/><span>Keep one source of truth.</span></h2><p>Adapters handle vendor differences while the operating model stays consistent. This is the part most platforms conveniently forget exists.</p></div><div className="capability-wall">{capabilities.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></section>
<section id="architecture" className="architecture-section"><div className="architecture-panel"><div className="section-intro compact"><span className="eyebrow">OPERATING ARCHITECTURE / 04</span><h2>Five planes.<br/><span>One operational fabric.</span></h2></div><div className="plane-stack">{planes.map(p=><div className="plane" key={p.tag}><span>{p.tag}</span><div><small>{p.title}</small><b>{p.items}</b></div><i>↗</i></div>)}</div></div><div className="integrity-panel"><span className="eyebrow">INTEGRITY BY DESIGN</span><div className="integrity-list"><div><b>PAYMENT</b><span>verified</span></div><div><b>ENTITLEMENT</b><span>explicit</span></div><div><b>NETWORK COMMAND</b><span>authorized</span></div><div><b>ACCOUNTING</b><span>reconciled</span></div><div><b>AUDIT</b><span>traceable</span></div></div><p>Critical state is not inferred from a button click. It is established by an authoritative source and correlated across the lifecycle.</p></div></section>
<section id="operators" className="operator-section"><div><span className="eyebrow">FOR OPERATORS / 05</span><h2>Built for the NOC,<br/><span>the billing desk and the field.</span></h2><p>One workspace for network teams, finance, support, sales agents and technicians. Dense where operations need density, calm where decisions need clarity.</p><div className="operator-tags"><span>NOC</span><span>ISP</span><span>WISP</span><span>HOTSPOT</span><span>FTTH</span><span>FIELD OPS</span></div></div><div className="operator-quote"><NetworkGlyph/><strong>Evidence over claims.</strong><span>Live state appears when its source is connected. Unknown stays unknown.</span><Link href="/net">Enter operations console ↗</Link></div></section>
<footer className="landing-footer"><div className="landing-brand"><span className="brand-symbol"><NetworkGlyph/></span><span><strong>JASLYN <em>NET</em></strong><small>HYBRID NETWORK OPERATING FABRIC</small></span></div><div><Link href="/login">Sign in</Link><Link href="/register">Create workspace</Link><Link href="/net">Console</Link></div><small>© 2026 Jaslyn Net · Vendor-neutral connectivity operations</small></footer>
</main>}