#!/usr/bin/env python3
"""Jaslyn Code Intelligence: language detection and experimental language generation."""
import json
import re
import sys
from pathlib import Path

EXTENSIONS = {
    ".js":"JavaScript", ".jsx":"JavaScript JSX", ".ts":"TypeScript", ".tsx":"TypeScript JSX", ".py":"Python", ".java":"Java", ".kt":"Kotlin", ".kts":"Kotlin", ".go":"Go", ".rs":"Rust", ".c":"C", ".h":"C/C++ Header", ".cpp":"C++", ".cc":"C++", ".cs":"C#", ".swift":"Swift", ".rb":"Ruby", ".php":"PHP", ".dart":"Dart", ".lua":"Lua", ".r":"R", ".scala":"Scala", ".ex":"Elixir", ".exs":"Elixir", ".hs":"Haskell", ".zig":"Zig", ".sol":"Solidity", ".sql":"SQL", ".html":"HTML", ".css":"CSS", ".scss":"SCSS", ".sh":"Shell", ".bash":"Shell", ".ps1":"PowerShell", ".json":"JSON", ".yaml":"YAML", ".yml":"YAML", ".toml":"TOML", ".md":"Markdown", ".vue":"Vue", ".svelte":"Svelte", ".clj":"Clojure", ".groovy":"Groovy",
}

SIGNATURES = [(r"\b(import|def|from)\b|if __name__", "Python"), (r"\b(const|let|function|console\.log)\b|=>", "JavaScript"), (r"\b(interface|type)\s+\w+|:\s*(string|number|boolean)\b", "TypeScript"), (r"\b(fn|let mut|impl|cargo)\b", "Rust"), (r"\b(package main|func main|go func)\b", "Go"), (r"\b(public static void|System\.out)\b", "Java"), (r"\b(SELECT|INSERT INTO|CREATE TABLE)\b", "SQL"), (r"<(!DOCTYPE|html|script)|</", "HTML"), (r"\b(def|class)\s+\w+.*:|\$\w+", "Ruby/PHP")]

def detect(source="", filename=""):
    suffix = Path(filename).suffix.lower()
    if suffix in EXTENSIONS:
        return {"language": EXTENSIONS[suffix], "confidence": 0.99, "method": "extension"}
    scores = {}
    for pattern, language in SIGNATURES:
        if re.search(pattern, source, re.I | re.M): scores[language] = scores.get(language, 0) + 1
    if not scores: return {"language": "Plain text / unknown", "confidence": 0.1, "method": "heuristic"}
    language, score = max(scores.items(), key=lambda pair: pair[1])
    return {"language": language, "confidence": min(0.95, 0.55 + score * 0.12), "method": "heuristic"}

def slugify(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "jaslyn-language"

def create_language(name, description="A language designed with Jaslyn", keywords=None, root=None):
    slug = slugify(name)
    root = Path(root or Path.cwd() / "data" / "languages") / slug
    root.mkdir(parents=True, exist_ok=True)
    words = keywords or ["let", "say", "if", "else"]
    grammar = "\n".join(["program = statement* ;", "statement = declaration | output ;", "declaration = 'let' identifier '=' value ;", "output = 'say' string ;", "value = string | number | identifier ;", f"keywords = {', '.join(repr(word) for word in words)} ;"])
    (root / "language.json").write_text(json.dumps({"name": name, "slug": slug, "description": description, "keywords": words, "version": "0.1.0", "status": "experimental"}, indent=2) + "\n")
    (root / "grammar.ebnf").write_text(grammar + "\n")
    (root / "examples.jaslynlang").write_text('let greeting = "Hello from ' + name + '"\nsay greeting\n')
    (root / "runtime.py").write_text('''#!/usr/bin/env python3\n# Experimental interpreter starter generated by Jaslyn.\nimport re\nimport sys\n\ndef run(source):\n    values = {}\n    for line in source.splitlines():\n        line = line.strip()\n        if not line: continue\n        match = re.match(r"let\\s+(\\w+)\\s*=\\s*['\"](.*?)['\"]$", line)\n        if match: values[match.group(1)] = match.group(2); continue\n        match = re.match(r"say\\s+(\\w+|['\"](.*?)['\"])$", line)\n        if match: print(values.get(match.group(1), match.group(2) or match.group(1))); continue\n        raise SyntaxError(f"Unsupported statement: {line}")\n\nif __name__ == "__main__": run(open(sys.argv[1], encoding="utf-8").read())\n''')
    return {"name": name, "slug": slug, "path": str(root), "files": ["language.json", "grammar.ebnf", "examples.jaslynlang", "runtime.py"], "status": "experimental-starter-created"}

def main(request):
    tool = request.get("tool")
    args = request.get("args") or {}
    if tool == "detect_language": return {"ok": True, "tool": tool, "detection": detect(str(args.get("source", "")), str(args.get("filename", "")))}
    if tool == "create_language": return {"ok": True, "tool": tool, "language": create_language(str(args.get("name", "Jaslyn Language")), str(args.get("description", "A language designed with Jaslyn")), args.get("keywords"))}
    return {"ok": False, "error": f"Code tool '{tool}' is not registered"}

if __name__ == "__main__":
    try: print(json.dumps(main(json.loads(sys.stdin.read() or "{}")), separators=(",", ":")))
    except Exception as exc: print(json.dumps({"ok": False, "error": str(exc)})); sys.exit(1)
